name: photostock
description: "Входное задание - Surf"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  elementary: ^3.0.0
  json_annotation: ^4.8.1
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0
  spider: ^4.2.2
  flutter_blurhash: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - lib/asset/item_list_asset/default_pic.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

